<?php

namespace Database\Seeders;

use App\Models\RawMaterial;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RawMaterialSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        RawMaterial::insert([
            // Used materials (20 entries)
            [
                'name' => 'PET (Polyethylene Terephthalate)',
                'description' => 'Clear plastic for beverage bottles',
                'price' => 27.80,
                'status' => 'used',
                'minimum_stock_alert' => 100,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'HDPE (High-Density Polyethylene)',
                'description' => 'Rigid plastic for containers and pipes',
                'price' => 32.15,
                'status' => 'used',
                'minimum_stock_alert' => 75,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'LDPE (Low-Density Polyethylene)',
                'description' => 'Flexible plastic for bags and wraps',
                'price' => 29.40,
                'status' => 'used',
                'minimum_stock_alert' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Polycarbonate (PC)',
                'description' => 'Impact-resistant for eyewear and electronics',
                'price' => 45.75,
                'status' => 'used',
                'minimum_stock_alert' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ABS (Acrylonitrile Butadiene Styrene)',
                'description' => 'Tough plastic for automotive parts and toys',
                'price' => 38.20,
                'status' => 'used',
                'minimum_stock_alert' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'TPE (Thermoplastic Elastomer)',
                'description' => 'Rubber-like material for seals and grips',
                'price' => 65.00,
                'status' => 'used',
                'minimum_stock_alert' => 35,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PMMA (Acrylic)',
                'description' => 'Transparent alternative to glass',
                'price' => 41.25,
                'status' => 'used',
                'minimum_stock_alert' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PLA (Polylactic Acid)',
                'description' => 'Biodegradable plastic for 3D printing',
                'price' => 47.80,
                'status' => 'used',
                'minimum_stock_alert' => 55,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Color Masterbatch - Black',
                'description' => 'Concentrated pigment for coloring',
                'price' => 18.50,
                'status' => 'used',
                'minimum_stock_alert' => 80,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'UV Stabilizer Additive',
                'description' => 'Prevents degradation from sunlight',
                'price' => 125.00,
                'status' => 'used',
                'minimum_stock_alert' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Flame Retardant Pellets',
                'description' => 'Enhances fire resistance',
                'price' => 155.75,
                'status' => 'used',
                'minimum_stock_alert' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Glass Fiber Reinforcement',
                'description' => 'Increases strength and stiffness',
                'price' => 32.45,
                'status' => 'used',
                'minimum_stock_alert' => 65,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Recycled PET Flakes',
                'description' => 'Post-consumer recycled material',
                'price' => 21.30,
                'status' => 'used',
                'minimum_stock_alert' => 150,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Antiblock Agent',
                'description' => 'Prevents film layers from sticking',
                'price' => 68.25,
                'status' => 'used',
                'minimum_stock_alert' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Impact Modifier',
                'description' => 'Improves toughness of rigid plastics',
                'price' => 95.40,
                'status' => 'used',
                'minimum_stock_alert' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Calcium Carbonate Filler',
                'description' => 'Reduces material costs',
                'price' => 12.75,
                'status' => 'used',
                'minimum_stock_alert' => 200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Titanium Dioxide',
                'description' => 'White pigment for opaque products',
                'price' => 38.90,
                'status' => 'used',
                'minimum_stock_alert' => 70,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Antistatic Agent',
                'description' => 'Reduces static electricity buildup',
                'price' => 47.35,
                'status' => 'used',
                'minimum_stock_alert' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Conductive Carbon Black',
                'description' => 'Adds electrical conductivity',
                'price' => 62.75,
                'status' => 'used',
                'minimum_stock_alert' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mold Release Agent',
                'description' => 'Prevents sticking in injection molds',
                'price' => 29.95,
                'status' => 'used',
                'minimum_stock_alert' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Recycled HDPE Pellets',
                'description' => 'Post-industrial recycled material',
                'price' => 26.40,
                'status' => 'used',
                'minimum_stock_alert' => 90,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Unused materials (10 entries)
            [
                'name' => 'Polystyrene (PS)',
                'description' => 'Foam packaging and disposable containers',
                'price' => 22.90,
                'status' => 'unused',
                'minimum_stock_alert' => 60,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nylon (PA)',
                'description' => 'Engineering plastic for gears and fibers',
                'price' => 51.30,
                'status' => 'unused',
                'minimum_stock_alert' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'POM (Acetal)',
                'description' => 'Precision parts for mechanical components',
                'price' => 58.90,
                'status' => 'unused',
                'minimum_stock_alert' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Antioxidant Compound',
                'description' => 'Reduces oxidation during processing',
                'price' => 89.95,
                'status' => 'unused',
                'minimum_stock_alert' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Slip Additive',
                'description' => 'Reduces friction in films',
                'price' => 73.60,
                'status' => 'unused',
                'minimum_stock_alert' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thermal Stabilizer',
                'description' => 'Maintains properties at high temperatures',
                'price' => 112.80,
                'status' => 'unused',
                'minimum_stock_alert' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lubricant Pellet',
                'description' => 'Improves flow during extrusion',
                'price' => 54.20,
                'status' => 'unused',
                'minimum_stock_alert' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bio-based Plasticizer',
                'description' => 'Eco-friendly alternative to phthalates',
                'price' => 88.50,
                'status' => 'unused',
                'minimum_stock_alert' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nucleating Agent',
                'description' => 'Improves crystallization rate',
                'price' => 79.60,
                'status' => 'unused',
                'minimum_stock_alert' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'PVC',
                'description' => 'Used in pipes',
                'price' => 18.75,
                'status' => 'unused',
                'minimum_stock_alert' => 40,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }

}
